# Generated by Django 3.0.3 on 2020-02-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
